### ISSUE TITLE
第二周09中σ的翻译问题

### ISSUE THREAD

**Issue by imSPS** [Yukong/Deeplearning.ai-Solutions#12]
第二周09逻辑回归的梯度下降与第二周02逻辑回归有部分内容翻译得不一样：
第二周02中参考部分
44
00:02:09,256 --> 00:02:11,471
sigmoid function applied to this quantity
由这个式子作为自变量的sigmoid函数中

第二周09中需修改部分
22
00:00:48,002 --> 00:00:51,363
follows your predictions y hat is
`y~定义如下 y~=a=sigma(z)`

应当为：
`y~定义如下 y~=a=sigmoid(z)`

**Comment by 0xMashiro** [comment]
谢谢你，已经改正错误并且将您加入到致谢名单
