### ISSUE TITLE
第2周第17课的时间轴好像有些问题

### ISSUE THREAD

**Issue by LeeJuly30** [Yukong/Deeplearning.ai-Solutions#16]
大概从20秒开始出现了字幕与语音、画面不同步，字幕文件一共3分56秒而实际视频只有3分43秒，我从coursera官网下载了英文字幕发现也有这个问题。

**Comment by 0xMashiro** [comment]
您的反馈已经收到，目前等待时轴人员重新处理。

**Comment by 0xMashiro** [comment]
我们这边的视频就是3分56秒的呢，应该是您下载的视频出现了问题，请您确认一下。

**Comment by LeeJuly30** [comment]
emmm.....  我上coursera官网又确认了一下还是3分43秒啊.....      你们那边是3分56就好，希望是我一个人的问题吧 - -..
