### ISSUE TITLE
02.What is a neural network字幕有点不同步21,22开始

### ISSUE THREAD

**Issue by markeloff** [Yukong/Deeplearning.ai-Solutions#17]
02.What is a neural network字幕有点不同步21,22开始

**Comment by liujinlong1992** [comment]
我用potplayer看这个视频，字幕不同步，就手动调整字幕，字幕遮挡视频内容就上下调整字幕位置，很方便。

**Comment by Yukong** [comment]
@liujinlong1992  你说的方法很棒！我可以把你说的方法放到文档里吗？

**Comment by 0xMashiro** [comment]
最根本的还是要找个人微调一下时间轴 @Yukong

**Comment by Yukong** [comment]
@AcceptedDoge 现在字幕组的情况你也知道，如果找个人专门负责这个的话怕是不太好找，所以暂时先定一个权宜之计。我还是推荐负责翻译某门课的同学就负责到底，把GTC/Github/时间轴都弄好，这样比较方便。我准备在第二门课翻译中推行这种政策

**Comment by 0xMashiro** [comment]
应该推荐审核人员修改的时候参考srt字幕，这样能保证质量。smartling和srt人员合并管理，不太现实，可以让他们有空的时间修一下srt的细节错误。

**Comment by Yukong** [comment]
@AcceptedDoge  是的，但是smartling没法上传srt文件，如果一个个从srt搬运到smartling，不仅少了翻译的乐趣，而且根据第一门课前两周课程的情况来看，大家的热情也不高。
所以我觉得一个人领了一个assignment，就把这个负责到底(srt/github/smartling)，不仅可以熟悉一个完整的大字幕组的翻译流程和操作，方便以后参加翻译，而且参与度高，积极性高，有利于字幕更快更好的上线。

**Comment by liujinlong1992** [comment]
@Yukong 可以啊
