### ISSUE TITLE
这个字幕什么时候cousera上会有？

### ISSUE THREAD

**Issue by 1558204459** [Yukong/Deeplearning.ai-Solutions#18]
这个字幕会被加到coursera上吗，如果会的话，那大概是什么时候？

**Comment by 0xMashiro** [comment]
工作是分开的，这个说不准。

**Comment by wizardforcel** [comment]
你可以加入 GTC 帮忙提交一下。但提交的东西貌似不能马上显示出来，需要复查什么的。

<https://translate-coursera.org/new_gtc/app/#/app/project_detail/b64cc4afb>

**Comment by 0xMashiro** [comment]
我已经在GTC里面两周了。

**Comment by Yukong** [comment]
目前GTC正在全力翻译中，预计半个月将会上线
