### ISSUE TITLE
字幕组加油啊，看英文版太费劲了。

### ISSUE THREAD

**Issue by ltcxjtu** [Yukong/Deeplearning.ai-Solutions#19]

**Comment by Yukong** [comment]
谢谢支持O(∩_∩)O
第一门课程我们尽力在半个月左右上线

**Comment by 0xMashiro** [comment]
当然你也要期望smartling和srt的字幕是内容同步的...这一点很难检查，不过我们会尽力完成。

**Comment by ltcxjtu** [comment]
感觉我也想在字幕组做一些事情，但英语听力好差。。。

**Comment by Yukong** [comment]
@ltcxjtu 欢迎有兴趣的小伙伴加入我们~翻译是听译+对照英文字幕，但也需要负责其他的同学，比如调时间轴、搬运已翻译字幕等等
