### ISSUE TITLE
字幕翻译质量问题

### ISSUE THREAD

**Issue by carefree0910** [Yukong/Deeplearning.ai-Solutions#21]
单从第三周的情况来看，脱离视频直接翻译英文字幕的情况有点多；由于英文字幕的质量堪忧，有不少地方都存在相当严重的误翻……
所以希望审阅or搬运的小伙伴在审阅or搬运时尽量对照视频过一遍翻译，我近期也会尽量修一修；不过我个人的能力还是很有限的，所以肯定有不少漏网之鱼……
如果有愿意校对的小伙伴的话，希望能够帮忙校对一下前两周的视频翻译，我则会先简单地修一遍第三周的视频翻译
提前感谢愿意帮忙校对的小伙伴了~

**Comment by zilingzhang** [comment]
看完了coursera C1和C3的vtt字幕 有些英文字幕直接来自语音识别.. 所以会有一些系统性的错 比如很多iterate错成innovate hype->type之类的 有些字幕时间交叠 甚至时间轴全错 还有漏字这些情况
翻译前最好先将英文字幕错修正 同时重新做断句对轴 那样处理过的文本译者理解起来会准确一点 
翻译时如果发现有费解的部分 要考虑原字幕有错的可能 不要硬翻
翻译后也要对着视频校对 因为有时候看视频才知道确切意思 还有公式字母大小写之类的细节 必要时重新调轴

**Comment by wizardforcel** [comment]
我觉得，很多地方太书面了，不够口语化。意思是对的，但是很别扭。
