### ISSUE TITLE
字幕为什么不现在就上传到coursera上呢

### ISSUE THREAD

**Issue by gromzhu** [Yukong/Deeplearning.ai-Solutions#22]
前几个视频已经可以有繁中字幕可以看了，简中已经翻译了不少了，为什么不上传一下呢

**Comment by Yukong** [comment]
已经上传了，现在正在组织审阅。因为提交给Coursera之后就不能更改了，所以要尽量保证翻译质量，现在可以暂时先下载一下GitHub的。

**Comment by eagleme90g** [comment]
辛苦了 大恩不言謝~

**Comment by liujinlong1992** [comment]
网易云课堂已经上线ng的深度学习系列课程了，目前上线的前3个课程都有中文字幕。

**Comment by Yukong** [comment]
@liujinlong1992  好的，马上把链接加到文档里
