### ISSUE TITLE
网易云课堂放出了带有中英文字幕的视频

### ISSUE THREAD

**Issue by Yves-X** [Yukong/Deeplearning.ai-Solutions#26]
之前有关注你们的进展，但好像官方英文字幕的质量就很有问题。今天发现了[这个东西](https://mooc.study.163.com/smartSpec/detail/1001319001.htm)：

> 由 deeplearning.ai 出品，网易引进的正版授权中文版深度学习工程师微专业课程

看了一下，就是Cousera课程的视频，网易云课堂压制了带有中英文字幕的版本，和Cousera的免费内容一样，只有视频部分，没有测验、作业和证书。
稍微看了几个印象中官方字幕有问题的地方，可以确定是经过了校正的。
希望这个信息对你们有用 :)

**Comment by Yves-X** [comment]
不好意思，更正一下，字幕是外挂的，并没有压制在视频内。
把浏览器请求的范围缩小到nos.netease.com，可以很容易地找到字幕文件。

**Comment by shmilyoo** [comment]
网易宣传的是官方国内合作，那么你们字幕组的dl.ai翻译工作下一步怎么办？和网易合作么？

_Sent from my HUAWEI NXT-AL10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eagleme90g** [comment]
請問 Yves-X "把浏览器请求的范围缩小到nos.netease.com，可以很容易地找到字幕文件。"
能否說詳細一點呢？

**Comment by Yukong** [comment]
@Yves-X  感谢提醒，会把这个链接和信息放到文档里

**Comment by Yukong** [comment]
@shmilyoo 我们会继续翻译，同时也会参考网易的翻译。没有条件去Coursera看视频和enroll课程的同学可以看网易的课程来替代，但我们也会继续翻译提供在Coursera的翻译版本。
由于国内已经可以方便的看到视频，srt文件可能不再继续维护，欢迎继续为本项目提出意见建议~

**Comment by onlyNata** [comment]
@Yves-X  “把浏览器请求的范围缩小到nos.netease.com，可以很容易地找到字幕文件”。 你可以具体说下吗？我想保存下载到本地看，每次看网页很不方便。 谢谢了~

**Comment by Yves-X** [comment]
@eagleme90g @onlyNata 
![Imgur](https://i.imgur.com/PlenKbX.png)

1. 按F12打开调试
2. 切换到网络选项卡
3. 加载页面
4. 过滤器填nos.netease.com
5. 图中标出的这种就是srt格式的字幕文件

**Comment by plmsmile** [comment]
真的有用，谢谢楼主啦。不过怎么才能下载高清视频呀？

**Comment by juwen** [comment]
按@Yves-X的方法，可以找到字幕的地址链接，用firefox 可以直接看到字幕，可以直接复制出来，保存。

**Comment by gethubwy** [comment]
您好，我按照您的方法，
按F12打开调试
切换到网络选项卡
加载页面
过滤器填nos.netease.com
然后没有发现在哪里有字幕文件，只有一个js文件，还希望请教您一下。
![image](https://user-images.githubusercontent.com/26212984/49262286-c1d8c400-f480-11e8-95af-b36dcdd48470.png)
@Yves-X

**Comment by tuji-sjp** [comment]
我也出现了gethubwy的问题，请问这是怎么回事呢？ @Yves-X @Yves-X @juwen
