### ISSUE TITLE
未来在Coursera上是否会支持你们的简中字幕？

### ISSUE THREAD

**Issue by yangtianming314** [Yukong/Deeplearning.ai-Solutions#3]
我看到 Coursera 上 deeplearning.ai 已经有开始有非英语的字幕，比如 Supervised Learning with Neural Networks 已经有繁体中文版本字幕，既然这个开源项目已经完成那么多简中翻译，是否会出现在 Coursera
 官网上呢？

**Comment by 0xMashiro** [comment]
会的，同时我们也在与Coursera反映服务器的问题，希望他们优化在中国的连接速度。
