### ISSUE TITLE
建议每个字幕都由多人轮审

### ISSUE THREAD

**Issue by xtttttttttx** [Yukong/Deeplearning.ai-Solutions#5]
浏览了很多已经审核通过的字幕
发现了很多问题:

1. 很多语句不符合中文语序
2. 太多直译，很少意译，导致看起来很突兀
3. 对句子的拆分有很多问题

提议建立审核小组重审所有字幕文件

**Comment by 0xMashiro** [comment]
放在github上面，所有人都可以对当前的字幕发起 pull requests 请求
