### ISSUE TITLE
关于2.2Logistic Regression的疑惑

### ISSUE THREAD

**Issue by athemeroy** [Yukong/Deeplearning.ai-Solutions#7]
以下是原文
--------
2

00:00:02,754 --> 00:00:04,820

regression this is a learning algorithm

逻辑回归,这是一种学习算法

3

00:00:04,820 --> 00:00:07,616

that you use when the output labels **why**

你使用它之时就知道**为什么**输出标签

4

00:00:07,616 --> 00:00:09,730

in a supervised learning problem are all

在一个监督学习问题中都

5

00:00:09,730 --> 00:00:12,101

either 0 or 1 so for binary

或者是0或者是1,所以对于二元

以下是疑惑
--------
我认为这里Ng的意思是：
This is a learning algorithm that you use when the output labels `y` in a supervised learning problem are all either 0 or 1.
它(Logistic Regression)是一种学习算法，使用在当监督学习的输出**标签y**要么是0要么是1的情况下。

而不是您翻译的`why`或者说`为什么`。
谢谢！

**Comment by 0xMashiro** [comment]
看到您的建议了，我们将去视频中确认一下，请耐心等待。

**Comment by 0xMashiro** [comment]
您的观点是正确的，十分感谢您！我们已经将您加入致谢名单。
