### ISSUE TITLE
Solution 在哪儿啊？或者什么时候可以上？

### ISSUE THREAD

**Issue by teruun** [Yukong/Deeplearning.ai-Solutions#8]
首先感谢大家的付出，小弟做了测试题之后不知道对不对，想找solution对照一下。可否抓紧把solution放上来啊？没钱买课程啊。。。
        此致敬礼

**Comment by 0xMashiro** [comment]
您好，旁听课程是不提供答案的。社区中提供答案的行为是违反了课程荣誉准则的，我们也不建议您通过网络搜索获得课程的答案。

**Comment by teruun** [comment]
哦，谢谢。我是看到你们在标题上写有solution，还以为中文版的会把答案也提供出来。不过还是谢谢你们。

**Comment by Yukong** [comment]
目前正在联系Andrew Ng教授解决关于版权的问题，在获准允许上传答案后会增加solution的内容~

**Comment by bianximo** [comment]
你可以在github里搜索一下deeplearning.ai,有一些人的观看笔记和自己做的习题答案，对照一下应该不构成侵权或者抄袭这样的行为吧？或者可不可以有人建一个qq群之类的，让国内学习这门课的同学可以互相讨论学习呢

**Comment by 0xMashiro** [comment]
私人记录笔记当然可以，如果明显表示公开分享答案违反课程荣誉准则，建议你了解一下荣誉准则的内容。如果要相互讨论学习，应该去课程论坛，或者私下建立小组。对于侵权和抄袭的，和翻译字幕后视频上传到别的网站一样，你觉得自己做了一件好事情，其实带来的是负面的影响。事实证明，很多时候的交流不过是一些人参考答案的借口。
